export const UserProject = {
    'jddiaz4@uc.cl': {id: '185', username:'Juan', name: 'Meet&Greet', technique: '3', lda: true, mf: false},
    'jddm11@gmail.com': {id: '185', username:'Juan', name: 'Meet&Greet', technique: '3', lda: false, mf: false},
    'aneyem@uc.cl': {id: '187', username:'Andres', name: 'Salud Estudiantil', technique: '3', lda: false, mf: false},
    'aneyem.academic@gmail.com': {id: '189', username:'Andres', name: 'Anatomia UC', technique: '3', lda: true, mf: false},
    'psanabria@uc.cl': {id: '191', username:'Pablo', name: 'BuyPass', technique: '3', lda: false, mf: false},

    'saalba@uc.cl': {id: '189', username:'Sebastian', name: 'Anatomia UC', technique: '3', lda: false, mf: false},
    'dacasas@uc.cl': {id: '189', username:'Diego', name: 'Anatomia UC', technique: '3', lda: true, mf: false},
    'faaraya1@uc.cl': {id: '189', username:'Fernando', name: 'Anatomia UC', technique: '3', lda: false, mf: false},
    'gacuchac@uc.cl': {id: '189', username:'Gabriel', name: 'Anatomia UC', technique: '3', lda: true, mf: false},
    'jdheysen@uc.cl': {id: '189', username:'Jurgen', name: 'Anatomia UC', technique: '3', lda: false, mf: false},
    'aamatte@uc.cl': {id: '189', username:'Andres', name: 'Anatomia UC', technique: '3', lda: true, mf: false},
    'tumunoz@uc.cl': {id: '189', username:'Tomas', name: 'Anatomia UC', technique: '3', lda: false, mf: false},
    'ratroncoso@uc.cl': {id: '189', username:'Rodrigo', name: 'Anatomia UC', technique: '3', lda: true, mf: false},
    'favasquez@uc.cl': {id: '189', username:'Felipe', name: 'Anatomia UC', technique: '3', lda: false, mf: false},

    'nlcampos@uc.cl': {id: '185', username:'Nicolas', name: 'Meet&Greet', technique: '3', lda: true, mf: false},
    'jmdelatorre@uc.cl': {id: '185', username:'Jose', name: 'Meet&Greet', technique: '3', lda: false, mf: false},
    'dafleiderman@uc.cl': {id: '185', username:'Daniel', name: 'Meet&Greet', technique: '3', lda: true, mf: false},
    'cbgarcia1@uc.cl': {id: '185', username:'Carlos', name: 'Meet&Greet', technique: '3', lda: false, mf: false},
    'gemoraga@uc.cl': {id: '185', username:'Gonzalo', name: 'Meet&Greet', technique: '3', lda: true, mf: false},
    'lrencoret1@uc.cl': {id: '185', username:'Lucas', name: 'Meet&Greet', technique: '3', lda: false, mf: false},
    'ajsalcedo@uc.cl': {id: '185', username:'Andres', name: 'Meet&Greet', technique: '3', lda: true, mf: false},
    'cesapunar@uc.cl': {id: '185', username:'Cristobal', name: 'Meet&Greet', technique: '3', lda: false, mf: false},
    'pasaratscheff@uc.cl': {id: '185', username:'Pedro', name: 'Meet&Greet', technique: '3', lda: true, mf: false},
    'pmgtapia@uc.cl': {id: '185', username:'Matias', name: 'Meet&Greet', technique: '3', lda: false, mf: false},

    'fdaguayo@uc.cl': {id: '193', username:'Fernando', name: 'DCC', technique: '3', lda: true, mf: false},
    'cjcastil@uc.cl': {id: '193', username:'Cristobal', name: 'DCC', technique: '3', lda: false, mf: false},
    'jidiaz3@uc.cl': {id: '193', username:'Javier', name: 'DCC', technique: '3', lda: true, mf: false},
    'gmgarcia@uc.cl': {id: '193', username:'Gonzalo', name: 'DCC', technique: '3', lda: false, mf: false},
    'negebauer@uc.cl': {id: '193', username:'Nicolas', name: 'DCC', technique: '3', lda: true, mf: false},
    'cnnaranj@uc.cl': {id: '193', username:'Carolina', name: 'DCC', technique: '3', lda: false, mf: false},
    'pfnieto@uc.cl': {id: '193', username:'Pablo', name: 'DCC', technique: '3', lda: true, mf: false},
    'daquiroz@uc.cl': {id: '193', username:'Daniela', name: 'DCC', technique: '3', lda: false, mf: false},
    'farojos@uc.cl': {id: '193', username:'Felipe', name: 'DCC', technique: '3', lda: true, mf: false},
    'pfsamaja@uc.cl': {id: '193', username:'Pablo', name: 'DCC', technique: '3', lda: false, mf: false},

    'cealvarez@uc.cl': {id: '187', username:'Camilo', name: 'Salud Estudiantil', technique: '3', lda: true, mf: false},
    'fjbaitelman@uc.cl': {id: '187', username:'Felipe', name: 'Salud Estudiantil', technique: '3', lda: false, mf: false},
    'jachicao@uc.cl': {id: '187', username:'Javier', name: 'Salud Estudiantil', technique: '3', lda: true, mf: false},
    'pndiaz1@uc.cl': {id: '187', username:'Patricio', name: 'Salud Estudiantil', technique: '3', lda: false, mf: false},
    'fagarri@uc.cl': {id: '187', username:'Francisco', name: 'Salud Estudiantil', technique: '3', lda: true, mf: false},
    'famarano@uc.cl': {id: '187', username:'Faustino', name: 'Salud Estudiantil', technique: '3', lda: false, mf: false},
    'ejmeza@uc.cl': {id: '187', username:'Esteban', name: 'Salud Estudiantil', technique: '3', lda: true, mf: false},
    'rpsaavedra@uc.cl': {id: '187', username:'Rodrigo', name: 'Salud Estudiantil', technique: '3', lda: false, mf: false},
    'dsinay@uc.cl': {id: '187', username:'Diego', name: 'Salud Estudiantil', technique: '3', lda: true, mf: false},
    'lezorich@uc.cl': {id: '187', username:'Lukas', name: 'Salud Estudiantil', technique: '3', lda: false, mf: false},

    'maldunate@uc.cl': {id: '191', username:'Manuel', name: 'BuyPass', technique: '3', lda: true, mf: false},
    'swgaete@uc.cl': {id: '191', username:'Sebastian', name: 'BuyPass', technique: '3', lda: false, mf: false},
    'gaibacache@uc.cl': {id: '191', username:'Guillerom', name: 'BuyPass', technique: '3', lda: true, mf: false},
    'galewinsohn@uc.cl': {id: '191', username:'Gad', name: 'BuyPass', technique: '3', lda: false, mf: false},
    'ppmiquel@uc.cl': {id: '191', username:'Pedro', name: 'BuyPass', technique: '3', lda: true, mf: false},
    'tpouliquen@uc.cl': {id: '191', username:'Tristan', name: 'BuyPass', technique: '3', lda: false, mf: false},
    'cirojas6@uc.cl': {id: '191', username:'Carlos', name: 'BuyPass', technique: '3', lda: true, mf: false},
    'iirubio@uc.cl': {id: '191', username:'Ivan', name: 'BuyPass', technique: '3', lda: false, mf: false},
    'jpsilva6@uc.cl': {id: '191', username:'Juan', name: 'BuyPass', technique: '3', lda: true, mf: false},
    'fisimon@uc.cl': {id: '191', username:'Felipe', name: 'BuyPass', technique: '3', lda: false, mf: false},

};
